/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.warmup;

import java.util.*; 

public class App {

    public Object[] map(Object[] input, MapFunction f) {
        Object[] output = new Object[input.length];
        for (int i = 0; i < input.length; i++) {
            output[i] = f.run(input[i]);
        }
        return output;
    }

    public Object[] flatten(Object[][] nested) {
        List<Object> result = new ArrayList<Object>();
        for (Object[] innerList : nested) {
        for (Object item : innerList) {
        result.add(item);
        }
        }
        Object[] out = new Object[result.size()];
        result.toArray(out);
        return out;
        }
        
    public String getGreeting() {
        return "Get me out of here..";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
