/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.warmup;

import java.util.*;

public class App {

    public <T> List<T> flatten(List<List<T>> nested) {
        List<T> result = new ArrayList<T>();
        for (List<T> innerList : nested) {
            for (T item : innerList) {
                result.add(item);
            }
        }
        return result;
    }

    public List<Object> map(List<Object> input, MapFunction f) {
        List<Object> output = new ArrayList<Object>();
        for (int i = 0; i < input.size(); i++) {
            output.add(f.run(input.get(i)));
        }
        return output;
    }

    public String getGreeting() {
        return "Get me out of here..";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
